/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ErrType.h"
#include "Stm32F103xx.h"
#include "Systick_interface.h"
#include "GPIO_interface.h"
#include "SSD_Interface.h"

#include "RCC_Interface.h"
#include "LED_Interface.h"

int main(void)
{
	uint8_t Local_u8RedLedCounter=INIT_VALUE_BY_ZERO;
	uint8_t Local_u8YelLedCounter=INIT_VALUE_BY_ZERO;
	uint8_t Local_u8GrnLedCounter=INIT_VALUE_BY_ZERO;


	/* enable rcc on the peripheral GPIOA GPIOB */
	RCC_voidAPB_2_EnableClk(IOPA_EN);
	RCC_voidAPB_2_EnableClk(IOPB_EN);
	RCC_voidAPB_2_EnableClk(IOPC_EN);

	/* prepare PinConfiguration struct for every SSD'Pins */
	PinConfig_t PinA11 = {.Port = PORTA,.PinNum =PIN11 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinA8  = {.Port = PORTA,.PinNum =PIN8  , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB15 = {.Port = PORTB,.PinNum =PIN15 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB14 = {.Port = PORTB,.PinNum =PIN14 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB13 = {.Port = PORTB,.PinNum =PIN13 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB12 = {.Port = PORTB,.PinNum =PIN12 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinA12 = {.Port = PORTA,.PinNum =PIN12 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinA15 = {.Port = PORTA,.PinNum =PIN15 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB8  = {.Port = PORTB,.PinNum =PIN8 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB9  = {.Port = PORTB,.PinNum =PIN9 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinB3  = {.Port = PORTB,.PinNum =PIN3 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};

	LED_Struct LEDYel= {.LED_u8ConnectionType = SOURCE_CONNECTION , .LED_u8PORT=PORTC , .LED_u8PIN = PIN13};
	LED_Struct LEDGre= {.LED_u8ConnectionType = SOURCE_CONNECTION , .LED_u8PORT=PORTC , .LED_u8PIN = PIN15};
	LED_Struct LEDRed1= {.LED_u8ConnectionType = SOURCE_CONNECTION , .LED_u8PORT=PORTA , .LED_u8PIN = PIN2};

	PinConfig_t PinC13 = {.Port = PORTC,.PinNum =PIN13 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinA2 = {.Port = PORTA,.PinNum =PIN2 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};
	PinConfig_t PinC15 = {.Port = PORTC,.PinNum =PIN15 , .Mode = OUTPUT_MAXSPEED_2MHZ ,.CNF_OutputMode=PUSH_PULL};


	/* CALL the function of SSD_voidPinInit */
	SSD_u8PinInit(&PinA11);
	SSD_u8PinInit(&PinA8 );
	SSD_u8PinInit(&PinB15);
	SSD_u8PinInit(&PinB14);
	SSD_u8PinInit(&PinB13);
	SSD_u8PinInit(&PinB12);
	SSD_u8PinInit(&PinA12);
	SSD_u8PinInit(&PinA15);
	SSD_u8PinInit(&PinB8);
	SSD_u8PinInit(&PinB9);
	SSD_u8PinInit(&PinB3);


	/* CALL the function of LED_voidPinInit */
	LED_u8PinInit(&PinC13);
	LED_u8PinInit(&PinA2);
	LED_u8PinInit(&PinC15);



	/* Loop forever */
	for(;;)
	{

		SSD_u8DisplayOFF(2,SSD_COMMON_CATHODE);
		SSD_u8DisplayOFF(1,SSD_COMMON_CATHODE);

		for(Local_u8RedLedCounter=INIT_VALUE_BY_ONE;Local_u8RedLedCounter<10;Local_u8RedLedCounter++)
		{
			LED_u8LedTurnON(&LEDRed1);
			SSD_u8DisplayOn(1, SSD_COMMON_CATHODE);
			SSD_u8DisplayNumber(1, SSD_COMMON_CATHODE, Local_u8RedLedCounter);
			SYSTICK_u8Delay_MS(1000);
		}



		for(Local_u8YelLedCounter=INIT_VALUE_BY_ONE;Local_u8YelLedCounter<4;Local_u8YelLedCounter++)
		{
			LED_u8LedTurnOff(&LEDRed1);
			LED_u8LedTurnON(&LEDYel);

			SSD_u8DisplayNumber(1, SSD_COMMON_CATHODE, Local_u8YelLedCounter);
			SYSTICK_u8Delay_MS(1000);

		}

		for(Local_u8GrnLedCounter=INIT_VALUE_BY_ONE;Local_u8GrnLedCounter<10;Local_u8GrnLedCounter++)
		{
			LED_u8LedTurnOff(&LEDRed1);
			LED_u8LedTurnOff(&LEDYel);
			LED_u8LedTurnON(&LEDGre);

			SSD_u8DisplayNumber(1, SSD_COMMON_CATHODE, Local_u8GrnLedCounter);
			SYSTICK_u8Delay_MS(1000);

		}


	}
}
